[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install", "pnpm prisma generate"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm prisma db push --accept-data-loss && node dist/main"
