[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install", "pnpm prisma generate"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm prisma migrate deploy && node dist/main"
